{
 "title": "Combined dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total wasted time (ms)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (server) (total_trapped_time_ms)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Total wasted time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(total_trapped_time_ms)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current connected clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(current_connected_clients)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current connected clients",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (server) (current_connected_clients)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(total_connects)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Concurrent connections over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (server) (current_connected_clients)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (latitude, longitude) (\n  tarpitted_clients{server=\"Telnet\"}\n)"
    },
    {
     "expr": "sum by (latitude, longitude) (\n  tarpitted_clients{server=\"UPnP\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (latitude, longitude) (\n  tarpitted_clients{server=\"MQTT\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (latitude, longitude) (\n  tarpitted_clients{server=\"CoAP\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (latitude, longitude) (\n  tarpitted_clients{server=\"SSH\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Location",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (country) (\n  tarpitted_clients{latitude!=\"0.000000\", longitude!=\"0.000000\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}