receivers:
  filelog:
    include:
      - /var/log/eventhorizon/*.jsonl
    start_at: beginning
    operators:
      - type: json_parser
        parse_from: body
        timestamp:
          parse_from: attributes.ts
          layout_type: strptime
          layout: "%Y-%m-%dT%H:%M:%S.%LZ"

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers:
        - filelog
      processors:
        - batch
      exporters:
        - debug
